sudo: required
services:
  - docker
  -

before_install:
  - docker build -t ainmutaqorrobin/docker-cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true ainmutaqorrobin/docker-cicd npm run test -- --coverage
